; ============================================================
; BetterBugs — Inno Setup Installer Script
; Builds: BetterBugs-Setup.exe
;
; Prerequisites (run build.bat first to generate these):
;   apps\api\betterbugs-api.exe
;   apps\mcp-server\dist\betterbugs-mcp.exe
;   apps\extension\dist\  (Chrome extension)
;   apps\dashboard\.next\standalone\  (Next.js)
; ============================================================

#define MyAppName      "BetterBugs"
#define MyAppVersion   "1.1.2"
#define MyAppPublisher "BetterBugs"
#define MyAppURL       "https://github.com/Unknnownnn/BetterBugs"
#define MyAppExeName   "BetterBugs-Launcher.vbs"
#define MyRootDir      ".."

[Setup]
AppId={{A3F7C2E1-88D4-4B9A-9C3E-F1D2E3B4C5A6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Compression
Compression=lzma2/ultra64
SolidCompression=yes
; Output
OutputDir=output
OutputBaseFilename=BetterBugs-Setup-{#MyAppVersion}
; Icons
SetupIconFile=assets\icon.ico
WizardStyle=modern
WizardResizable=yes
; Privileges
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
; Uninstall
UninstallDisplayIcon={app}\betterbugs-api.exe
UninstallDisplayName={#MyAppName}
; Version info
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription=BetterBugs — AI-native bug capture platform
; Min Windows version (Windows 10)
MinVersion=10.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; ============================================================
; Custom wizard pages — collect MongoDB URI + API key
; ============================================================
[Code]
var
  ConfigPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  ConfigPage := CreateInputQueryPage(
    wpSelectDir,
    'Configure BetterBugs',
    'Enter your database and API settings',
    'These settings are required to connect to your MongoDB instance. ' +
    'You can use a free MongoDB Atlas cluster or a local MongoDB server.'
  );
  ConfigPage.Add('MongoDB URI (e.g. mongodb+srv://user:pass@cluster.mongodb.net/bugcatcher):', False);
  ConfigPage.Add('Project API Key (e.g. my-secret-key):', False);

  // Defaults
  ConfigPage.Values[0] := 'mongodb://localhost:27017';
  ConfigPage.Values[1] := 'dev-key';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = ConfigPage.ID then
  begin
    if Trim(ConfigPage.Values[0]) = '' then
    begin
      MsgBox('MongoDB URI is required.', mbError, MB_OK);
      Result := False;
      Exit;
    end;
    if Trim(ConfigPage.Values[1]) = '' then
    begin
      MsgBox('Project API Key is required.', mbError, MB_OK);
      Result := False;
      Exit;
    end;
  end;
end;

// Write .env after install completes
procedure CurStepChanged(CurStep: TSetupStep);
var
  EnvContent: string;
  EnvFile: string;
begin
  if CurStep = ssPostInstall then
  begin
    EnvFile := ExpandConstant('{app}\.env');
    EnvContent :=
      '# BetterBugs Configuration' + #13#10 +
      '# Generated by installer on ' + GetDateTimeString('yyyy-mm-dd', '-', ':') + #13#10 +
      '' + #13#10 +
      '# Server' + #13#10 +
      'PORT=3001' + #13#10 +
      'GIN_MODE=release' + #13#10 +
      '' + #13#10 +
      '# MongoDB' + #13#10 +
      'MONGODB_URI=' + ConfigPage.Values[0] + #13#10 +
      'MONGODB_DATABASE=bugcatcher' + #13#10 +
      '' + #13#10 +
      '# Security' + #13#10 +
      'API_KEY_SECRET=betterbugs-secret-' + ConfigPage.Values[1] + #13#10 +
      'ENCRYPTION_KEY=betterbugs-32-byte-encryption-key!!' + #13#10 +
      '' + #13#10 +
      '# MCP Server' + #13#10 +
      'BETTERBUGS_API_URL=http://localhost:3001' + #13#10 +
      'BETTERBUGS_API_KEY=' + ConfigPage.Values[1] + #13#10 +
      '' + #13#10 +
      '# Rate Limiting' + #13#10 +
      'RATE_LIMIT_REQUESTS=100' + #13#10 +
      'RATE_LIMIT_WINDOW=60' + #13#10 +
      '' + #13#10 +
      '# Storage' + #13#10 +
      'STORAGE_QUOTA_SESSIONS=1000' + #13#10 +
      'STORAGE_RETENTION_DAYS=30';
    SaveStringToFile(EnvFile, EnvContent, False);

    // Also write mcp-server .env
    EnvFile := ExpandConstant('{app}\mcp-server\.env');
    EnvContent :=
      'BETTERBUGS_API_URL=http://localhost:3001' + #13#10 +
      'BETTERBUGS_API_KEY=' + ConfigPage.Values[1];
    SaveStringToFile(EnvFile, EnvContent, False);
  end;
end;

[Tasks]
Name: "desktopicon";     Description: "{cm:CreateDesktopIcon}";      GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}";  GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1
Name: "startupicon";     Description: "Start BetterBugs on Windows login"; GroupDescription: "Startup:"; Flags: unchecked

[Files]
; ── API binary ──────────────────────────────────────────────
Source: "{#MyRootDir}\apps\api\betterbugs-api.exe"; DestDir: "{app}"; Flags: ignoreversion

; ── MCP server binary ───────────────────────────────────────
Source: "{#MyRootDir}\apps\mcp-server\dist\betterbugs-mcp.exe"; DestDir: "{app}\mcp-server"; Flags: ignoreversion

; ── Next.js Dashboard (standalone) ──────────────────────────────────────────
; Copy the full standalone folder (contains server.js + its own .next/server)
Source: "{#MyRootDir}\apps\dashboard\.next\standalone\*"; DestDir: "{app}\dashboard"; Flags: ignoreversion recursesubdirs createallsubdirs
; Static chunks must live at {app}\dashboard\.next\static  (server.js serves _next/static from here)
Source: "{#MyRootDir}\apps\dashboard\.next\standalone\.next\static\*"; DestDir: "{app}\dashboard\.next\static"; Flags: ignoreversion recursesubdirs createallsubdirs
; Public assets
Source: "{#MyRootDir}\apps\dashboard\public\*"; DestDir: "{app}\dashboard\public"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

; ── Chrome Extension ─────────────────────────────────────────
Source: "{#MyRootDir}\apps\extension\dist\*"; DestDir: "{app}\extension"; Flags: ignoreversion recursesubdirs createallsubdirs

; ── Launcher scripts ─────────────────────────────────────────
Source: "assets\BetterBugs-Launcher.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "assets\BetterBugs-ControlPanel.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "assets\start-services.bat";      DestDir: "{app}"; Flags: ignoreversion
Source: "assets\stop-services.bat";       DestDir: "{app}"; Flags: ignoreversion

; ── Assets & README ──────────────────────────────────────────
Source: "assets\icon.ico";               DestDir: "{app}"; Flags: ignoreversion
Source: "assets\README.txt";             DestDir: "{app}"; Flags: ignoreversion isreadme

[Icons]
; Start Menu
Name: "{group}\{#MyAppName}";             Filename: "wscript.exe"; Parameters: """{app}\{#MyAppExeName}"""; IconFilename: "{app}\icon.ico"
Name: "{group}\Stop BetterBugs";          Filename: "{app}\stop-services.bat"
Name: "{group}\Extension folder";         Filename: "{app}\extension"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

; Desktop
Name: "{autodesktop}\{#MyAppName}"; Filename: "wscript.exe"; Parameters: """{app}\{#MyAppExeName}"""; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

; Startup
Name: "{autostartup}\{#MyAppName}"; Filename: "wscript.exe"; Parameters: """{app}\{#MyAppExeName}"""; Tasks: startupicon

[Run]
; Launch after install
Filename: "wscript.exe"; Parameters: """{app}\{#MyAppExeName}"""; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{app}\stop-services.bat"; Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}\.env"
Type: filesandordirs; Name: "{app}\mcp-server\.env"
Type: filesandordirs; Name: "{app}\logs"
